### PR TITLE
feat: add Scroll Alpha Testnet

### PR DESCRIPTION
**Pull request by dghelm**
Hoping to add deployed contracts on Scroll Alpha Testnet.

Original contract deployment output viewable [here](https://gist.github.com/dghelm/c661daac1e99a40e3d63e27575acab1b).

_Note:_ I'm unsure why running `yarn generate` also modified polygon and avax files, so please provide input on if this was an error on my end.

Edit:
This is to follow through on [this Aave Governance Proposal](https://governance.aave.com/t/deploy-aave-v3-on-scroll-testnet/11861 ) and progress to this point has been aided by help from @foodaka

### CODE REVIEW

**Comment by sakulstra** [comment]
> Note: I'm unsure why running yarn generate also modified polygon and avax files, so please provide input on if this was an error on my end.

it's currently a problem with the ci not updating automatically when irs change onchain.
It's fine to update here <3

Will get back soon to you as I have to follow up on what this is exactly - am i correct to assume it's related to: https://governance.aave.com/t/deploy-aave-v3-on-scroll-testnet/11861 ?

**Comment by dghelm** [comment]
> Will get back soon to you as I have to follow up on what this is exactly - am i correct to assume it's related to: https://governance.aave.com/t/deploy-aave-v3-on-scroll-testnet/11861 ?

This is correct. Sorry to not call it out in the PR description. Edited.

> At least for now i'd hold off from adding non verified contracts. Also i'm not 100% sold yet on adding networks not supported on the existing uis. We'll need to discuss internally and eventually adjust the readme, guidlines.

You've identified the correct block explorer -- and I understand the hesitation to trust a self-hosted, open-source "source of truth" here over something more centrally protected like Etherscan.

That said, Blockscout supports the same verification APIs as Etherscan, but unfortunately is seeing [an issue](https://github.com/blockscout/blockscout/issues/7150) around correctly indexing (and verifying) contracts created through factories. I have run the verifier on what I can at this point though and will keep you posted as we work through issues with Blockscout.

**Comment by dghelm** [comment]
> Also i'm not 100% sold yet on adding networks not supported on the existing uis.

I'm just realizing I may have misunderstood what you mean here. Are you suggesting the library wouldn't support projects that aren't included in Aave's frontend UI repo? Because @foodaka asked us to make the PR here so that we could get _into_ that repo since it uses this library as a dependency. Might be a bit of a chicken and an egg issue :)

**Review by sakulstra — APPROVED** [review]

**Comment by dghelm** [comment]
Thanks for the approval! Just to document, Scroll's Blockscout can now verify all contracts except for `FlashLoanLogic`, `L2Pool-Implementation` and `PoolConfiguration-Implementation`.  Looks like Optimism Goerli verifies the latter 2, so we'll keep looking into how to address that.

@sakulstra As for npm library release cycles, is that something external contributors can help with, or is it best to just keep an eye on releases?

**Comment by sakulstra** [comment]
@dghelm , it's released now. Wanted to include some other additions as well.

**Pull request merged**
