### PR TITLE
feat: add Scroll Sepolia testnet

### PR DESCRIPTION
**Pull request by dghelm**
Following up on #112, adding Scroll Sepolia testnet addresses. Faucet fixes applied in #133 already applied.

Updates `viem` to support Scroll Sepolia's chain info.

Address Output:
https://gist.github.com/dghelm/7fe68f0a524f30846e1142721c081d84

Contracts verified on [Blockscout](https://sepolia-blockscout.scroll.io/).

### CODE REVIEW

**Comment by dghelm** [comment]
FYI @sakulstra : The contract addresses for everything (except the faucet) match Scroll Alpha, in case that helps make review quicker.

**Comment by sakulstra** [comment]
@dghelm any idea where the yarn lock changes are coming from? seems like the package source has changed which is a bit weird (looks okay as it's now yarnpkg but the change is still awkward)

**Comment by dghelm** [comment]
@sakulstra  -- I think it comes from me trying to fix merge conflicts and maybe just deleting and regenerating the `yarn.lock` to make sure I didn't mess anything up.

Updating the `viem` package will change something there, but so many diffs from an outside contributor is not a good look for a security-critical package!

Let me raise a new PR.

**Comment by dghelm** [comment]
Actually, I don't think there's a good way to avoid this unless I just don't commit the changes on the `yarn.lock` file.

Just tried a fresh branch and just running `yarn` is going to make this happen. I can run `yarn install --frozen-lockfile` before `yarn add viem@^1.7.0`, but the additional changes to the lock file still occur.

That said, running `yarn why` on a few packages shows a bit more what packages have triggered them:

```
❯ yarn why fsevents
yarn why v1.22.5
[1/4] Why do we have the module "fsevents"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "fsevents@2.3.3"
info Reasons this module exists
   - "tsup#chokidar" depends on it
   - Hoisted from "tsup#chokidar#fsevents"
   - Hoisted from "tsup#rollup#fsevents"

❯ yarn why @esbuild/android-arm64
yarn why v1.22.5
[1/4] Why do we have the module "@esbuild/android-arm64"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@esbuild/android-arm64@0.18.20"
info Reasons this module exists
   - "tsup#esbuild" depends on it
   - Hoisted from "tsup#esbuild#@esbuild#android-arm64"
```

Any guidance on the best path forward? Also, do I need to be worrying about `package-lock.json`?

**Comment by sakulstra** [comment]
@dghelm didn't notice there was such a mess on our side :(

resolved here: https://github.com/bgd-labs/aave-address-book/pull/213, you you rebase on that (also updated viem so no changes should be needed on your side. Sorry for the mess)

**Comment by dghelm** [comment]
@sakulstra Thanks for taking care of it in the main branch! To clean things up, I've moved to #215 and will close this thread.

**Pull request closed without merging**
